### ISSUE TITLE
Illegible Code Snippets

### ISSUE THREAD

**Issue by aayush420** [mgechev/blog.mgechev.com#43]
### The Problem
Your posts are great. But they all have a problem in common. Your `code snippets` are **not easy to read**.
![Original screenshot with illegible code snippet](https://user-images.githubusercontent.com/16898783/48981328-f69ff080-f0f9-11e8-8420-c60c3a40bdd6.png)

### The Solution
Remove the font-family `fira code` from your css. I've unchecked the font-family css style in inspector tools and it totally work fine. (You can see the font-family unchecked in the right for pre code styles)
![Screenshot with font-family removed](https://user-images.githubusercontent.com/16898783/48981340-0cadb100-f0fa-11e8-8131-bed2e4cf1dbe.png)

**Comment by mgechev** [comment]
Dropped fira code. Looks like the ligatures make the snippets harder to read.
